version: '3.8'
services:
  dev-db:
    image: mysql
    ports:
      - 9000:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - we-want-more
  
  test-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=we_want_more
    networks:
      - we-want-more
networks:
  we-want-more: